export const GITHUB_TABLE_NAME = 'GithubKeys';

export const GITHUB_TABLE_CREATE = `CREATE TABLE IF NOT EXISTS ${GITHUB_TABLE_NAME} (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    store_key VARCHAR(100) UNIQUE NOT NULL,
    value VARCHAR(255)
);`;

export const GITHUB_INDEXES_CREATE = `CREATE INDEX git_key_index ON ${GITHUB_TABLE_NAME} (store_key);`;
